version: '3.8'

services:
  second-brain-ocr:
    # For local builds:
    build: .

    # For Azure Container Registry (comment out 'build' above and uncomment below):
    # image: yourregistryname.azurecr.io/second-brain-ocr:latest

    # For Docker Hub:
    # image: your-username/second-brain-ocr:latest

    container_name: second-brain-ocr
    restart: unless-stopped

    environment:
      # Directory to watch (inside container)
      - WATCH_DIR=/brain-notes

      # File watching mode
      # USE_POLLING=true: Checks directory every N seconds (reliable, works with Nextcloud web uploads)
      # USE_POLLING=false: Event-based watching (instant detection, only for direct file additions)
      - USE_POLLING=${USE_POLLING:-true}
      - POLLING_INTERVAL=${POLLING_INTERVAL:-180}

      # Azure Document Intelligence
      - AZURE_DOC_INTELLIGENCE_ENDPOINT=${AZURE_DOC_INTELLIGENCE_ENDPOINT}
      - AZURE_DOC_INTELLIGENCE_KEY=${AZURE_DOC_INTELLIGENCE_KEY}

      # Azure OpenAI
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - AZURE_OPENAI_EMBEDDING_DEPLOYMENT=${AZURE_OPENAI_EMBEDDING_DEPLOYMENT:-text-embedding-ada-002}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2024-02-01}

      # Azure AI Search
      - AZURE_SEARCH_ENDPOINT=${AZURE_SEARCH_ENDPOINT}
      - AZURE_SEARCH_KEY=${AZURE_SEARCH_KEY}
      - AZURE_SEARCH_INDEX_NAME=${AZURE_SEARCH_INDEX_NAME:-second-brain-notes}

      # Processing options
      - BATCH_SIZE=${BATCH_SIZE:-10}

      # State file location
      - STATE_FILE=/app/data/processed_files.json

      # Webhook notifications (optional)
      - WEBHOOK_URL=${WEBHOOK_URL:-}

    volumes:
      # Mount your Nextcloud brain-notes directory
      # Adjust the path on the left side to match your Synology path
      - /volume1/nextcloud/data/YOUR_USER/files/brain-notes:/brain-notes:ro

      # Persistent storage for application state
      - ./data:/app/data

    # Optional: If you need to configure logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
