line-length = 120

[lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "N",
    "UP",
    "B",
    "C4",
    "SIM",
]
ignore = [
    "SIM117",  # Allow nested with statements in tests for readability
]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
